package com.ezfinanz.common.enums;

public enum ApplicationStatus {
    DRAFT,
    EMAIL_VERIFICATION,
    PHONE_VERIFICATION,
    KYC_PENDING,
    KYC_COMPLETED,
    ELIGIBILITY_PENDING,
    ELIGIBLE,
    PARTIALLY_ELIGIBLE,
    NOT_ELIGIBLE,
    TERMS_PENDING,
    BANK_PENDING,
    DECLARATION_PENDING,
    SELFIE_PENDING,
    SELFIE_UNDER_REVIEW,
    SELFIE_APPROVED,
    SELFIE_REJECTED,
    APPROVED,
    DISBURSEMENT_PENDING,
    DISBURSED,
    REJECTED
}
